[package]
name = "test-redis-pooling"
version = "0.1.0"
edition = "2018"

[dependencies]
rocket = "0.4.0"
redis = "0.10.0"

[dependencies.rocket_contrib]
version = "0.4.0"
default-features = false
features = ["redis_pool"]
